pgpyshop:
  build: .
  user: docker
  command: pserve development.pg.ini --reload
  ports:
    - 8090:6543
  volumes:
    - .:/srv/pyshop
  links:
    - postgresql:postgresql.localdomain
  environment:
    PYSHOP_CONFIG_URI: development.pg.ini


postgresql:
  image: postgres:9.4
  ports:
    - 5432:5432


caddy:
  image: abiosoft/caddy:no-stats
  ports:
    - 80:80
    - 8080:2015
    - 443:443
  links:
    - pgpyshop:pgpyshop
  volumes:
    - ./Caddyfile:/etc/Caddyfile
    - ../.caddy:/etc/caddycerts
  environment:
    CADDYPATH: /etc/caddycerts
    ACME_AGREE: 'true'
